### ISSUE TITLE
Memory usage for original model

### ISSUE THREAD

**Issue by TamasSL** [andylolu2/speedtoxify#1]
Hello!

Do you know what is the expected memory usage of the ```original``` ONNX model? On my setup it's 600MB and based on the [Memory Usage](https://github.com/andylolu2/speedtoxify#memory-usage) paragraph I was expecting it to be lower. Also it looks like for the ```original``` model,  ```deduplicate_shared_layers``` doesn't actually remove anything from the graph. Is that expected?

Thank you!

**Comment by andylolu2** [comment]
`original` is a larger than `original-small` so that's about the amount of memory usage that I'll expect.
It also uses BERT instead of ALBERT, which doesn't have shared weights, so it's going to have both a larger file size and memory usage.
